#!/usr/bin/env bash
# A Bash script that finds the PID of the process by its name.

PID=$(pgrep -x "4-to_infinity_and_beyond")

#check if the PID was found 
if [ -n "$PID" ]; then 
  pkill "$PID"
  echo "Process 4-to_infinity_and_beyond (PID: $PID) has been terminated."
else 
  echo "Process 4-to_infinity_and_beyond not found."
fi
