#!/usr/bin/env bash
# Trap SIGTERM and execute the echo command instead of exiting

trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
